all:
	doxygen Doxyfile 
clean:
	rm -f $(NP2_ROOT)/documentation/html/*.* 
	rm -f $(NP2_ROOT)/documentation/html/search/*.* 
	rmdir $(NP2_ROOT)/documentation/html/search 
	rmdir $(NP2_ROOT)/documentation/html 

