#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "$0 <ELF File>"
else
	$NP2_QEMU/qemu-system-arm -M netduinoplus2 -nographic -kernel $1 -chardev stdio,mux=on,id=terminal -serial /dev/null -serial /dev/null -serial /dev/null -serial chardev:terminal -serial /dev/null -serial chardev:terminal -monitor chardev:terminal
fi;
